FROM ubuntu:20.04

# Install Test::Nginx
RUN apt update
RUN apt install -y cpanminus make
RUN cpanm --notest Test::Nginx

# Install development utils
RUN apt install -y sudo git gawk curl nano vim inetutils-ping

WORKDIR /apisix

ENV PERL5LIB=.:$PERL5LIB

ENTRYPOINT ["tail", "-f", "/dev/null"]
